project_id = "tbtprqgydggwetfgmbcp"

[functions.bulk-onboard]
verify_jwt = false

[functions.admin-manage]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.send-broadcast]
verify_jwt = false

[functions.seed-users]
verify_jwt = false
